stages:
  - build

variables:
  REGISTRY: "docker.io"
  IMAGE_NAME: "erickdaniel0/dockerscout"
  DOCKER_TLS_CERTDIR: ""

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    BUILDX_CONTEXT_NAME: "gitlab-ci-buildx"
  script:
    - echo "Configurando Docker Buildx"
    - docker context create $BUILDX_CONTEXT_NAME --docker host=unix:///var/run/docker.sock
    - docker context use $BUILDX_CONTEXT_NAME
    - docker buildx create --use --name builder-instance

    - echo "Generando metadatos de la imagen"
    - export DOCKER_IMAGE_TAG="$REGISTRY/$IMAGE_NAME:latest"
    - export SHORT_SHA="L_$(echo $CI_COMMIT_SHA | cut -c 1-7)"  # Agregar prefijo `g`

    - echo "Iniciando sesión en Docker Hub"
    - echo "$DOCKER_HUB_PAT" | docker login --username "$DOCKER_HUB_USER" --password-stdin

    - echo "Construyendo y subiendo la imagen Docker"
    - docker buildx build --push --label "org.opencontainers.image.revision=$CI_COMMIT_SHA" --tag $DOCKER_IMAGE_TAG --tag "$REGISTRY/$IMAGE_NAME:$SHORT_SHA" .

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_MERGE_REQUEST_ID'
